version: "2.0"

services:

  traefik:
    image: "traefik:v2.5"
    container_name: "traefik"
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
      - "--entryPoints.websecure.address=:443"
      - "--certificatesResolvers.letsencrypt.acme.email=github.${DOMAIN}"
      - "--certificatesResolvers.letsencrypt.acme.storage=acme.json"
      - "--certificatesResolvers.letsencrypt.acme.tlsChallenge=true"
      - "--certificatesResolvers.letsencrypt.acme.httpChallenge=true"
      - "--certificatesResolvers.letsencrypt.acme.httpChallenge.entryPoint=web"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./resource/acme.json:/acme.json"
    labels:
      # Redirect all HTTP to HTTPS permanently
      - "traefik.enable=true"
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:[a-z-.]+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"    
    restart: unless-stopped

  code:
    image: lscr.io/linuxserver/code-server    
    container_name: "code-server"
    logging:
        driver: none
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.code.rule=Host(`code.${DOMAIN}`)"
      - "traefik.http.routers.code.entrypoints=websecure"
      - "traefik.http.routers.code.tls.certresolver=letsencrypt" 
      - "traefik.http.services.code.loadbalancer.server.port=8443"  
      - "traefik.http.routers.code.middlewares=traefik-forward-auth" 
    ports:
      - 8443:8443
    restart: unless-stopped 

  cryptpad:
    image: promasu/cryptpad:nginx
    container_name: cryptpad
    stdin_open: true
    volumes:
      - ./resource/cryptpad/data/blob:/cryptpad/blob
      - ./resource/cryptpad/data/block:/cryptpad/block
      - ./resource/cryptpad/customize:/cryptpad/customize
      - ./resource/cryptpad/data/data:/cryptpad/data
      - ./resource/cryptpad/data/files:/cryptpad/datastore
      - ./resource/cryptpad/data/config.js:/cryptpad/config/config.js
    environment:
      - "CPAD_MAIN_DOMAIN=office.${DOMAIN}"
      - "CPAD_SANDBOX_DOMAIN=edit.office.${DOMAIN}"
      - "CPAD_HTTP2_DISABLE=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.office.rule=Host(`office.${DOMAIN}`, `edit.office.${DOMAIN}`)"
      - "traefik.http.routers.office.entrypoints=websecure"
      - "traefik.http.routers.office.tls.certresolver=letsencrypt" 
      - "traefik.http.services.office.loadbalancer.server.port=80"  

  
  whoami:
    image: "traefik/whoami"
    container_name: "whoami"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.${DOMAIN}`)"
      - "traefik.http.routers.whoami.entrypoints=websecure"
      - "traefik.http.routers.whoami.tls.certresolver=letsencrypt"
    restart: unless-stopped

  main-website:
    image: "ghcr.io/talidemestre/homepage-react:master"
    container_name: "main-website"
    stdin_open: true
    logging:
        driver: none
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.mainwebsite.rule=Host(`${DOMAIN}`) || Host(`www.${DOMAIN}`)"
      - "traefik.http.routers.mainwebsite.entrypoints=websecure"
      - "traefik.http.routers.mainwebsite.tls.certresolver=letsencrypt" 
      - "traefik.http.services.mainwebsite.loadbalancer.server.port=3000"


  traefik-forward-auth:
    image: thomseddon/traefik-forward-auth:latest
    container_name: "traefik-forward-auth" 
    environment:
      - LOG_LEVEL=DEBUG
      - WHITELIST=${WHITELIST}
      - DEFAULT_PROVIDER=generic-oauth
      - PROVIDERS_GENERIC_OAUTH_AUTH_URL=https://github.com/login/oauth/authorize
      - PROVIDERS_GENERIC_OAUTH_TOKEN_URL=https://github.com/login/oauth/access_token
      - PROVIDERS_GENERIC_OAUTH_USER_URL=https://api.github.com/user
      - PROVIDERS_GENERIC_OAUTH_CLIENT_ID=${GITHUB_OAUTH_CLIENT_ID}
      - PROVIDERS_GENERIC_OAUTH_CLIENT_SECRET=${GITHUB_OAUTH_CLIENT_SECRET}      
      - SECRET=${RANDOM_SECRET}
      - INSECURE_COOKIE=true # Example assumes no https, do not use in production
    labels:
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.address=http://traefik-forward-auth:4181"
      - "traefik.http.middlewares.traefik-forward-auth.forwardauth.authResponseHeaders=X-Forwarded-User"
      - "traefik.http.services.traefik-forward-auth.loadbalancer.server.port=4181"
    restart: unless-stopped
